name: Docker

on: [push, pull_request, workflow_call]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          verbose: true
          dockerfile: "Dockerfile"

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Cache Docker Images
        uses: ScribeMD/docker-cache@0.3.6
        with:
            key: docker-${{ runner.os }}-${{ hashFiles('**/Dockerfile') }}

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag rss2jext:$(date +%s)
